// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ITwitter is an autogenerated mock type for the ITwitter type
type ITwitter struct {
	mock.Mock
}

// ListenToMentions provides a mock function with given fields: username
func (_m *ITwitter) ListenToMentions(username string) (<-chan interface{}, error) {
	ret := _m.Called(username)

	var r0 <-chan interface{}
	if rf, ok := ret.Get(0).(func(string) <-chan interface{}); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Stop provides a mock function with given fields:
func (_m *ITwitter) Stop() {
	_m.Called()
}

// Tweet provides a mock function with given fields: text, inReplyTo, images
func (_m *ITwitter) Tweet(text string, inReplyTo int64, images [][]byte) error {
	ret := _m.Called(text, inReplyTo, images)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64, [][]byte) error); ok {
		r0 = rf(text, inReplyTo, images)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
